# Generated by Django 4.2 on 2023-05-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_upload', models.BooleanField()),
            ],
        ),
    ]
