# Generated by Django 4.2 on 2023-05-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsu', '0002_user_music_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_upload',
            new_name='is_uploading',
        ),
    ]
