# Generated by Django 4.2 on 2023-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsu', '0003_rename_is_upload_user_is_uploading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_uploading',
            new_name='finish',
        ),
    ]
