# Generated by Django 4.2 on 2023-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsu', '0004_rename_is_uploading_user_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
