# Generated by Django 4.2 on 2023-05-03 16:46

from django.db import migrations, models
import minsu.models


class Migration(migrations.Migration):

    dependencies = [
        ('minsu', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music_file_converted',
            field=models.FileField(null=True, upload_to=minsu.models.directory_path),
        ),
    ]
